### ISSUE TITLE
Documentation, how to use

### ISSUE THREAD

**Issue by p4trizio** [KirillMetrik/Toggl2Jira#1]
Hi I am interested in using Toggl2Jira, can someone explain what to do to use it?
Thank you

**Comment by KirillMetrik** [comment]
Hi Patrizio, you'll need .Net 4.5 installed on your machine. You can download the latest release here: https://github.com/KirillMetrik/Toggl2Jira/releases .
Just run the app, fill-in your credentials for Toggl and Jira, and click the POST button. The tool will take descriptions from your Toggl entries and if there is a Jira ticket number in the beginning of the description, the tool will save that time entry as a worklog for the respective Jira issue.
Please let me know if that makes sense, I'll add user guide with some screenshots later.
Thanks!
